language: python
python:
   - 2.5
   - 2.6
   - 2.7
install:
   - pip install -r test_requirements.txt
   - python setup.py install

script:
  # We run things in separate directory to avoid nose importing the unbuilt
  # version
  - mkdir empty
  - pushd empty
  - nosetests ../traits
  - popd empty

notifications:
  email: false
